export RUST_BACKTRACE=1
export RUST_LOG=info 
#export COUCHBASE_CONN=couchbase://server1,server2,server3
#export COUCHBASE_USER=userhere
export COUCHBASE_PASSWORD=REPLACEACTUALPASSWORDHERE
export COUCHBASE_BUCKET=MASTER
export LD_LIBRARY_PATH=/usr/local/cargo/lib:$LD_LIBRARY_PATH

docker run --rm -d -e RUST_BACKTRACE -e LD_LIBRARY_PATH -e RUST_LOG -e COUCHBASE_CONN -e COUCHBASE_USER -e COUCHBASE_PASSWORD -e COUCHBASE_BUCKET -p 8888:8888 cbcouchpool
